In [2]:
# NumPy Installation
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 3.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.6 MB 3.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.6 MB 3.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 3.5 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.6 MB 3.4 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 3.4 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 3.0 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 3.0 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.6 MB 2.4 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.6 MB 2.3 MB/s eta 0:00:04
   ----------------- ---------------------- 5.5/12.6 MB 2.2 MB/s eta 0:00:04
   ---

In [3]:
import numpy as np

In [4]:
numpy_array=np.array([1,2,3,4,5])

In [7]:
print(type(numpy_array))

<class 'numpy.ndarray'>


In [9]:
twoDArray=np.array([[1,2,3],[4,5,6]])
print(twoDArray)

[[1 2 3]
 [4 5 6]]


In [10]:
threeDArray=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
np.arange(3,21,3)


array([ 3,  6,  9, 12, 15, 18])